services:
  books_app:
    image: "nomisreual/books:latest"
    depends_on:
      - books_db
    environment:
      PRODUCTION_DATABASE: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@books_db/${POSTGRES_DB}"
  books_db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_DB: ${POSTGRES_DB}
  books_webserver:
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CERTS}:${CERTS_NGINX}:ro
    depends_on:
      - books_app
