"""Added dummy user table.

Revision ID: 72105e9be5bf
Revises: 1a08edbb7c0b
Create Date: 2024-01-26 21:05:01.968969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72105e9be5bf'
down_revision = '1a08edbb7c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
