"""Switched FK location between Publisher and Address.

Revision ID: 10ca069d9661
Revises: 48cfee69ff40
Create Date: 2024-02-02 13:44:08.260359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ca069d9661'
down_revision = '48cfee69ff40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint('addresses_publisher_id_key', type_='unique')
        batch_op.drop_constraint('addresses_publisher_id_fkey', type_='foreignkey')
        batch_op.drop_column('publisher_id')

    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['address_id'])
        batch_op.create_foreign_key(None, 'addresses', ['address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('address_id')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('addresses_publisher_id_fkey', 'publishers', ['publisher_id'], ['id'])
        batch_op.create_unique_constraint('addresses_publisher_id_key', ['publisher_id'])

    # ### end Alembic commands ###
