services:
  books_app:
    image: "nomisreual/books:latest"
    depends_on:
      - books_db
    environment:
      PRODUCTION_DATABASE: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@books_db/${POSTGRES_DB}"
    ports:
      - "5000:5000"
  books_db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_DB: ${POSTGRES_DB}
