name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: src/books
    
    - name: Build the Docker image
      run: docker build -t books:latest -f src/books/Dockerfile
